//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimulatedEcology {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EventDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimulatedEcology.EventDescriptions", typeof(EventDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bears produced..
        /// </summary>
        internal static string BearsProduced {
            get {
                return ResourceManager.GetString("BearsProduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bears trapped..
        /// </summary>
        internal static string BearsTrapped {
            get {
                return ResourceManager.GetString("BearsTrapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} units of lumber harvested..
        /// </summary>
        internal static string LumberHarvested {
            get {
                return ResourceManager.GetString("LumberHarvested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lumberjacks fired..
        /// </summary>
        internal static string LumberjackFired {
            get {
                return ResourceManager.GetString("LumberjackFired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lumberjacks hired..
        /// </summary>
        internal static string LumberjackHired {
            get {
                return ResourceManager.GetString("LumberjackHired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lumberjacks mawled..
        /// </summary>
        internal static string LumberjacksMawled {
            get {
                return ResourceManager.GetString("LumberjacksMawled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sapplings became trees..
        /// </summary>
        internal static string SapplingsMatured {
            get {
                return ResourceManager.GetString("SapplingsMatured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sapplings spawned..
        /// </summary>
        internal static string SapplingsSpawned {
            get {
                return ResourceManager.GetString("SapplingsSpawned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} trees became elder trees..
        /// </summary>
        internal static string TreesMatured {
            get {
                return ResourceManager.GetString("TreesMatured", resourceCulture);
            }
        }
    }
}
